### ISSUE TITLE
support for multiple identities

### ISSUE THREAD

**Issue by joehand** [licensezero/licensezero-cli#9]
Does the command line support using multiple identities/licensors (e.g. one for personal and one for business)? I was able to get two identities in there but did not see how to manage to licensors, etc.

**Comment by kemitchell** [comment]
@joehand, good question!

The CLI does not support this at present. Nor does the current development version of the Go port, https://github.com/licensezero/cli, which will replace the Node CLI in the next couple of weeks.

The Node CLI _did_ support this early on. Is this something I should prioritize for you, in the Go CLI? If so, might I ask you to elaborate a little bit on the use case. Is the idea that you will use the CLI from two points of view:

1. As Joe Hand, independent developer, buying licenses for himself, and selling licenses for his own work?

2. As SomeCo, Inc., a company that sells licenses?

Please note that License Zero does _not_ currently support _buying_ licenses for companies, rather than people. Each person at a company needs to buy (and potentially expense) the licenses they need, as they would for, say, SublimeText. Licensors _can_ cut "site license"-style deals on their own, without going through the system. But the system itself doesn't automate that process.

**Comment by joehand** [comment]
>  Is this something I should prioritize for you, in the Go CLI?

If there is a workaround (for example, I can manually maintain two config files), that'd fine. I understand the nuances of multiple identities can get complex! I'm more in the exploratory stage of how I can use License Zero personally and at Code for Science & Society. If I do end up moving forward in both uses, I'll let you know and help support this case as much as I can.

> Is the idea that you will use the CLI from two points of view:
>    1. As Joe Hand, independent developer, buying licenses for himself, and selling licenses for his own work?
>
>   2. As SomeCo, Inc., a company that sells licenses?

Yes, exactly.

**Comment by kemitchell** [comment]
@joehand, the new Go CLI stores all persistent configuration in JSON data files within `$XDG_CONFIG/licensezero/`, which is usually `$HOME/.config/licensezero` on unixy systems. The relevant files for your identity data---name, email, jurisdiction---is `./identity.json` for the new client. The file for licensor ID and access token is `./licensor.json`.

Both are simple Object JSON serializations. The keys are `name`, `email`, and `jurisdiction` or `licensorID` and `token`, respectively. All values are strings.

I can't recall offhand if the current Node CLI allows overriding the config directory location with an env var. The forthcoming Go client certainly does: [code where it happens](https://github.com/licensezero/cli/blob/0e15b40de2ccda4e2397b4d1a237750f40393029/data/config.go#L7). As a band-aid, you could invoke commands like `licensezero publish` a la:

```bash
$ LICENSEZERO_CONFIG="$HOME/.config/licensezero-css" licensezero identify --name "Code for Science and Society, Inc." --jurisdiction "US-DE" --email "test@example.com"
$ LICENSEZERO_CONFIG="$HOME/.config/licensezero-css" licensezero register
$ LICENSEZERO_CONFIG="$HOME/.config/licensezero-css" licensezero token --licensor "$ID_FROM_WEBPAGE"
```

**Comment by kemitchell** [comment]
@joehand, I'm going to go ahead and close, since it looks like `LICENSEZERO_CONFIG`, which I implemented with testing in mind, will cover your need for now. I'll also mention that the new Go CLI has `licensezero backup`, which will write a dated tarball of your current config directory to CWD. Might come in handy.
